language: php

php:
  - 7.2
  - 7.1
  - 7
  - 5.6
  - 5.5

before_script:
  - composer self-update
  - composer update
  - if [ $(phpenv version-name) != "5.6" ]; then composer require --dev phpstan/phpstan; fi

script:
  - composer run-script test
  - if [ $(phpenv version-name) != "5.6" ]; then composer run-script phpstan; fi
