language: php

matrix:
    include:
      - php: 7.2
        env: XPHPENV="NEW"
      - php: 7.1
        env: XPHPENV="NEW"
      - php: 7.0
        env: XPHPENV="NEW"
      - php: 5.6
        env: XPHPENV="OLD"
      - php: 5.5
        env: XPHPENV="OLD"

before_script:
  - composer self-update
  - if [ $XPHPENV = "NEW" ]; then composer install; fi
  - if [ $XPHPENV = "OLD" ]; then composer install --no-dev; fi
  - if [ $XPHPENV = "OLD" ]; then composer require phpunit/phpunit "^3"; fi

script:
  - composer run-script test
  - if [ $XPHPENV = "NEW" ]; then composer run-script phpstan; fi
