site_name: LoggerEssentials
site_url: https://github.com/LoggerEssentials/LoggerEssentials
site_description: A fully standards-compliant logging component library (PSR-3) with some useful wrappers and adapters.
repo_url: https://github.com/LoggerEssentials/LoggerEssentials
pages:
- ['index.md', 'Home']
- ['user-guide/install.md', 'User Guide']
- ['user-guide/getting-started.md', 'User Guide']
- ['components/loggers/LoggerCollection.md', 'Components', 'Loggers']
- ['components/loggers/ArrayLogger.md', 'Components', 'Loggers']
- ['components/loggers/CallbackLogger.md', 'Components', 'Loggers']
- ['components/loggers/ErrorLogLogger.md', 'Components', 'Loggers']
- ['components/loggers/LoggerCollection.md', 'Components', 'Loggers']
- ['components/loggers/ResourceLogger.md', 'Components', 'Loggers']
- ['components/loggers/StreamLogger.md', 'Components', 'Loggers']
- ['components/loggers/SyslogLogger.md', 'Components', 'Loggers']
- ['components/common/ExtendedLogger.md', 'Components', 'Common']
- ['components/common/ExtendedPsrLoggerWrapper.md', 'Components', 'Common']
- ['components/formatters/CallbackFormatter.md', 'Components', 'Formatters']
- ['components/formatters/ContextJsonFormatter.md', 'Components', 'Formatters']
- ['components/formatters/DateTimeFormatter.md', 'Components', 'Formatters']
- ['components/formatters/FormatFormatter.md', 'Components', 'Formatters']
- ['components/formatters/MaxLengthFormatter.md', 'Components', 'Formatters']
- ['components/formatters/MessagePrefixFormatter.md', 'Components', 'Formatters']
- ['components/formatters/NobrFormatter.md', 'Components', 'Formatters']
- ['components/formatters/PassThroughFormatter.md', 'Components', 'Formatters']
- ['components/formatters/ReplaceFormatter.md', 'Components', 'Formatters']
- ['components/formatters/TemplateFormatter.md', 'Components', 'Formatters']
- ['components/formatters/TrimFormatter.md', 'Components', 'Formatters']
- ['components/filters/CallbackFilter.md', 'Components', 'Filters']
- ['components/filters/ExcludeLogLevelFilter.md', 'Components', 'Filters']
- ['components/filters/LogLevelRangeFilter.md', 'Components', 'Filters']
- ['components/filters/MaxLogLevelFilter.md', 'Components', 'Filters']
- ['components/filters/MinLogLevelFilter.md', 'Components', 'Filters']
- ['components/filters/RegularExpressionFilter.md', 'Components', 'Filters']
- ['components/extenders/CallbackExtender.md', 'Components', 'Extenders']
- ['components/extenders/ContextExtender.md', 'Components', 'Extenders']
- ['components/extenders/StacktraceExtender.md', 'Components', 'Extenders']
